### ISSUE TITLE
email template

### ISSUE THREAD

**Issue by muralihr** [siddhantvinchurkar/Bengaluru-Plog-Run#2]
You received this email because you're an area ambassador for Bengaluru Plog Run.
--
Bengaluru Plog Run - 1234 Main Street - Anywhere, MA - 56789

Change it to look like this 
**GoNative Bengaluru Plog Run.**

replace 1234 Main Street - Anywhere, MA - 56789-
with 
http://bengaluru.plog.run #IamPlasticLess #GoNative

**Comment by siddhantvinchurkar** [comment]
Fixed!
